"""
Schema definitions for LLM-based cloud orchestration planning.

This module defines the data structures and system prompts used for planning
with Large Language Models. It includes Pydantic models for structured planning
output and the system prompt that guides LLM behavior.
"""
from typing import Any, Dict, List

from pydantic import BaseModel, Field

PLANNER_SYSTEM_PROMPT = """
You are a cloud orchestration planner.

Rules:
- Break the goal into executable steps
- Each step must be safe, minimal, and reversible
- Output ONLY valid JSON
- Use unique task IDs (t1, t2, t3...)
- Dependencies must reference previous task IDs
- No explanations, no markdown

Output format:
{{
  "goal": "...",
  "tasks": [
    {{
      "id": "t1",
      "name": "...",
      "action": "...",
      "params": {{}},
      "depends": []
    }}
  ]
}}
"""


class LLMTask(BaseModel):
    """
    Represents a single task in an LLM-generated plan.

    Each task is an atomic unit of work that can be executed independently
    or with dependencies on other tasks. Tasks are identified by unique IDs
    and describe actions to be performed on cloud resources.

    Attributes:
        id: Unique task identifier (e.g., "t1", "t2"). Used for referencing
            in dependency lists and task tracking.
        name: Human-readable name describing the task purpose.
        action: The action to perform, typically a cloud operation or command.
        params: Dictionary of parameters passed to the action. Defaults to empty dict.
        depends: List of task IDs that must complete before this task starts.
            Defaults to empty list (no dependencies).
    """

    id: str = Field(..., description="Unique task id, e.g. t1, t2")
    name: str
    action: str
    params: Dict[str, Any] = {}
    depends: List[str] = []


class LLMPlan(BaseModel):
    """
    Represents a complete plan generated by an LLM for achieving a goal.

    A plan consists of a goal description and an ordered list of tasks with
    their dependencies. The plan can be executed by traversing tasks according
    to their dependency relationships.

    Attributes:
        goal: The high-level goal or objective that this plan aims to achieve.
        tasks: List of LLMTask objects representing the steps to accomplish the goal.
    """

    goal: str
    tasks: List[LLMTask]
